import { z } from "zod";

const BASE = process.env.PUBLIC_DATA_URL ?? "https://public-data-production.up.railway.app";

const covidSchema = z
  .object({
    iso_code: z.string(),
    continent: z.string().nullable(),
    location: z.string().nullable(),
    date: z.string().nullable(),
    total_cases: z.number().nullable(),
    new_cases: z.number().nullable(),
    new_cases_smoothed: z.number().nullable(),
    total_cases_per_million: z.number().nullable(),
    new_cases_per_million: z.number().nullable(),
    new_cases_smoothed_per_million: z.number().nullable(),
    total_deaths: z.number().nullable(),
    new_deaths: z.number().nullable(),
    new_deaths_smoothed: z.number().nullable(),
    total_deaths_per_million: z.number().nullable(),
    new_deaths_per_million: z.number().nullable(),
    new_deaths_smoothed_per_million: z.number().nullable(),
    reproduction_rate: z.number().nullable(),
    icu_patients: z.number().nullable(),
    icu_patients_per_million: z.number().nullable(),
    hosp_patients: z.number().nullable(),
    hosp_patients_per_million: z.number().nullable(),
    weekly_icu_admissions: z.number().nullable(),
    weekly_icu_admissions_per_million: z.number().nullable(),
    weekly_hosp_admissions: z.number().nullable(),
    weekly_hosp_admissions_per_million: z.number().nullable(),
    total_tests: z.number().nullable(),
    new_tests: z.number().nullable(),
    total_tests_per_thousand: z.number().nullable(),
    new_tests_per_thousand: z.number().nullable(),
    new_tests_smoothed: z.number().nullable(),
    new_tests_smoothed_per_thousand: z.number().nullable(),
    positive_rate: z.number().nullable(),
    tests_per_case: z.number().nullable(),
    tests_units: z.string().nullable(),
    total_vaccinations: z.number().nullable(),
    people_vaccinated: z.number().nullable(),
    people_fully_vaccinated: z.number().nullable(),
    total_boosters: z.number().nullable(),
    new_vaccinations: z.number().nullable(),
    new_vaccinations_smoothed: z.number().nullable(),
    total_vaccinations_per_hundred: z.number().nullable(),
    people_vaccinated_per_hundred: z.number().nullable(),
    people_fully_vaccinated_per_hundred: z.number().nullable(),
    total_boosters_per_hundred: z.number().nullable(),
    new_vaccinations_smoothed_per_million: z.number().nullable(),
    new_people_vaccinated_smoothed: z.number().nullable(),
    new_people_vaccinated_smoothed_per_hundred: z.number().nullable(),
    stringency_index: z.number().nullable(),
    population_density: z.number().nullable(),
    median_age: z.number().nullable(),
    aged_65_older: z.number().nullable(),
    aged_70_older: z.number().nullable(),
    gdp_per_capita: z.number().nullable(),
    extreme_poverty: z.number().nullable(),
    cardiovasc_death_rate: z.number().nullable(),
    diabetes_prevalence: z.number().nullable(),
    female_smokers: z.number().nullable(),
    male_smokers: z.number().nullable(),
    handwashing_facilities: z.number().nullable(),
    hospital_beds_per_thousand: z.number().nullable(),
    life_expectancy: z.number().nullable(),
    human_development_index: z.number().nullable(),
    population: z.number().nullable(),
    excess_mortality_cumulative_absolute: z.number().nullable(),
    excess_mortality_cumulative: z.number().nullable(),
    excess_mortality: z.number().nullable(),
    excess_mortality_cumulative_per_million: z.number().nullable(),
  })
  .transform((r) => ({
    isoCode: r.iso_code,
    continent: r.continent,
    location: r.location,
    date: r.date,
    totalCases: r.total_cases,
    newCases: r.new_cases,
    newCasesSmoothed: r.new_cases_smoothed,
    totalCasesPerMillion: r.total_cases_per_million,
    newCasesPerMillion: r.new_cases_per_million,
    newCasesSmoothedPerMillion: r.new_cases_smoothed_per_million,
    totalDeaths: r.total_deaths,
    newDeaths: r.new_deaths,
    newDeathsSmoothed: r.new_deaths_smoothed,
    totalDeathsPerMillion: r.total_deaths_per_million,
    newDeathsPerMillion: r.new_deaths_per_million,
    newDeathsSmoothedPerMillion: r.new_deaths_smoothed_per_million,
    reproductionRate: r.reproduction_rate,
    icuPatients: r.icu_patients,
    icuPatientsPerMillion: r.icu_patients_per_million,
    hospPatients: r.hosp_patients,
    hospPatientsPerMillion: r.hosp_patients_per_million,
    weeklyIcuAdmissions: r.weekly_icu_admissions,
    weeklyIcuAdmissionsPerMillion: r.weekly_icu_admissions_per_million,
    weeklyHospAdmissions: r.weekly_hosp_admissions,
    weeklyHospAdmissionsPerMillion: r.weekly_hosp_admissions_per_million,
    totalTests: r.total_tests,
    newTests: r.new_tests,
    totalTestsPerThousand: r.total_tests_per_thousand,
    newTestsPerThousand: r.new_tests_per_thousand,
    newTestsSmoothed: r.new_tests_smoothed,
    newTestsSmoothedPerThousand: r.new_tests_smoothed_per_thousand,
    positiveRate: r.positive_rate,
    testsPerCase: r.tests_per_case,
    testsUnits: r.tests_units,
    totalVaccinations: r.total_vaccinations,
    peopleVaccinated: r.people_vaccinated,
    peopleFullyVaccinated: r.people_fully_vaccinated,
    totalBoosters: r.total_boosters,
    newVaccinations: r.new_vaccinations,
    newVaccinationsSmoothed: r.new_vaccinations_smoothed,
    totalVaccinationsPerHundred: r.total_vaccinations_per_hundred,
    peopleVaccinatedPerHundred: r.people_vaccinated_per_hundred,
    peopleFullyVaccinatedPerHundred: r.people_fully_vaccinated_per_hundred,
    totalBoostersPerHundred: r.total_boosters_per_hundred,
    newVaccinationsSmoothedPerMillion: r.new_vaccinations_smoothed_per_million,
    newPeopleVaccinatedSmoothed: r.new_people_vaccinated_smoothed,
    newPeopleVaccinatedSmoothedPerHundred: r.new_people_vaccinated_smoothed_per_hundred,
    stringencyIndex: r.stringency_index,
    populationDensity: r.population_density,
    medianAge: r.median_age,
    aged65Older: r.aged_65_older,
    aged70Older: r.aged_70_older,
    gdpPerCapita: r.gdp_per_capita,
    extremePoverty: r.extreme_poverty,
    cardiovascDeathRate: r.cardiovasc_death_rate,
    diabetesPrevalence: r.diabetes_prevalence,
    femaleSmokers: r.female_smokers,
    maleSmokers: r.male_smokers,
    handwashingFacilities: r.handwashing_facilities,
    hospitalBedsPerThousand: r.hospital_beds_per_thousand,
    lifeExpectancy: r.life_expectancy,
    humanDevelopmentIndex: r.human_development_index,
    population: r.population,
    excessMortalityCumulativeAbsolute: r.excess_mortality_cumulative_absolute,
    excessMortalityCumulative: r.excess_mortality_cumulative,
    excessMortality: r.excess_mortality,
    excessMortalityCumulativePerMillion: r.excess_mortality_cumulative_per_million,
  }));

export type CovidRow = z.output<typeof covidSchema>;

const countrySchema = z.object({
  iso_code: z.string(),
  location: z.string(),
  continent: z.string().nullable(),
});

export async function fetchCovidData(
  isoCode: string,
  start?: string,
  end?: string,
): Promise<CovidRow[]> {
  const params = new URLSearchParams();
  if (start) params.set("start", start);
  if (end) params.set("end", end);
  const qs = params.toString();
  const url = `${BASE}/covid/${isoCode}${qs ? `?${qs}` : ""}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`public-data API error: ${res.status}`);
  return z.array(covidSchema).parse(await res.json());
}

export async function fetchCountries(): Promise<z.infer<typeof countrySchema>[]> {
  const res = await fetch(`${BASE}/covid/countries`);
  if (!res.ok) throw new Error(`public-data API error: ${res.status}`);
  return z.array(countrySchema).parse(await res.json());
}
