groups:
  - name: tasks_recording_rules
    interval: 15s
    rules:
      - record: tasks_total_count
        expr: tasks_total

      - record: tasks_open_count
        expr: tasks_open

      - record: tasks_overdue_count
        expr: tasks_overdue

      - record: tasks_due_7d
        expr: tasks_due_next_7d
