apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma
spec:
  template:
    spec:
      containers:
        - name: kuma
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            initialDelaySeconds: 30
          readinessProbe:
            initialDelaySeconds: 15
          startupProbe:
            failureThreshold: 18
