apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: kuma-config
    behavior: merge
    literals:
      - LOG_LEVEL=warn
      - ENVIRONMENT=production

replicas:
  - name: kuma
    count: 3

images:
  - name: kuma-kuma
    newName: ghcr.io/charlesponti/kuma
    newTag: v1.0.0
