apiVersion: 1
datasources:
  - name: SQLite (prod)
    type: simpod-sqlite-datasource
    access: proxy
    isDefault: true
    jsonData:
      path: /var/lib/grafana/data/tasks.sqlite
    secureJsonData: {}
    editable: true
