# Flyway configuration for @pontistudios/db
# https://documentation.red-gate.com/flyway

flyway.url=jdbc:mysql://127.0.0.1:3306/labs
flyway.user=labs
flyway.password=labs_password
flyway.locations=filesystem:src/migrations
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
