name: deploy-earth-prod

on:
  workflow_dispatch:

concurrency:
  group: deploy-earth-prod-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_EARTH_INTELLIGENCE }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
